[2024-05-19T16:25:41.947+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T16:25:41.954+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: disney_api_to_s3.save_to_s3 manual__2024-05-19T16:24:37.174707+00:00 [queued]>
[2024-05-19T16:25:41.957+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: disney_api_to_s3.save_to_s3 manual__2024-05-19T16:24:37.174707+00:00 [queued]>
[2024-05-19T16:25:41.957+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-19T16:25:41.962+0000] {taskinstance.py:2330} INFO - Executing <Task(S3FileTransformOperator): save_to_s3> on 2024-05-19 16:24:37.174707+00:00
[2024-05-19T16:25:41.964+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=283) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T16:25:41.965+0000] {standard_task_runner.py:63} INFO - Started process 285 to run task
[2024-05-19T16:25:41.965+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'disney_api_to_s3', 'save_to_s3', 'manual__2024-05-19T16:24:37.174707+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/api_disney.py', '--cfg-path', '/tmp/tmpe6ktxm_y']
[2024-05-19T16:25:41.966+0000] {standard_task_runner.py:91} INFO - Job 67: Subtask save_to_s3
[2024-05-19T16:25:41.984+0000] {task_command.py:426} INFO - Running <TaskInstance: disney_api_to_s3.save_to_s3 manual__2024-05-19T16:24:37.174707+00:00 [running]> on host 620090466bc8
[2024-05-19T16:25:42.012+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='disney_api_to_s3' AIRFLOW_CTX_TASK_ID='save_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-05-19T16:24:37.174707+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-19T16:24:37.174707+00:00'
[2024-05-19T16:25:42.012+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T16:25:42.018+0000] {s3.py:652} INFO - Downloading source S3 file tmp/2024-05-19/disney_data.json
[2024-05-19T16:25:42.022+0000] {base.py:84} INFO - Using connection ID 'aws_s3' for task execution.
[2024-05-19T16:25:42.023+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-05-19T16:25:42.153+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T16:25:42.154+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/s3.py", line 653, in execute
    if not source_s3.check_for_key(self.source_s3_key):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 135, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 922, in check_for_key
    obj = self.head_object(key, bucket_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 135, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 902, in head_object
    return self.get_conn().head_object(Bucket=bucket_name, Key=key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 946, in _make_api_call
    api_params = self._emit_api_params(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1072, in _emit_api_params
    self.meta.events.emit(
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/handlers.py", line 282, in validate_bucket_name
    if not VALID_BUCKET.search(bucket) and not VALID_S3_ARN.search(bucket):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
[2024-05-19T16:25:42.159+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=disney_api_to_s3, task_id=save_to_s3, run_id=manual__2024-05-19T16:24:37.174707+00:00, execution_date=20240519T162437, start_date=20240519T162541, end_date=20240519T162542
[2024-05-19T16:25:42.164+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 67 for task save_to_s3 (expected string or bytes-like object, got 'NoneType'; 285)
[2024-05-19T16:25:42.197+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T16:25:42.203+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T16:25:42.204+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
