[2024-05-19T20:36:24.224+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T20:36:24.243+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-04-23T00:00:00+00:00 [queued]>
[2024-05-19T20:36:24.250+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_s3.process_parquet_files scheduled__2023-04-23T00:00:00+00:00 [queued]>
[2024-05-19T20:36:24.251+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-19T20:36:24.271+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_parquet_files> on 2023-04-23 00:00:00+00:00
[2024-05-19T20:36:24.281+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1607) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T20:36:24.285+0000] {standard_task_runner.py:63} INFO - Started process 1625 to run task
[2024-05-19T20:36:24.290+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'silver_s3', 'process_parquet_files', 'scheduled__2023-04-23T00:00:00+00:00', '--job-id', '362', '--raw', '--subdir', 'DAGS_FOLDER/silver_s3.py', '--cfg-path', '/tmp/tmps3h0myka']
[2024-05-19T20:36:24.296+0000] {standard_task_runner.py:91} INFO - Job 362: Subtask process_parquet_files
[2024-05-19T20:36:24.379+0000] {task_command.py:426} INFO - Running <TaskInstance: silver_s3.process_parquet_files scheduled__2023-04-23T00:00:00+00:00 [running]> on host 620090466bc8
[2024-05-19T20:36:24.481+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_s3' AIRFLOW_CTX_TASK_ID='process_parquet_files' AIRFLOW_CTX_EXECUTION_DATE='2023-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-23T00:00:00+00:00'
[2024-05-19T20:36:24.482+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T20:36:24.507+0000] {base.py:84} INFO - Using connection ID 'aws_s3' for task execution.
[2024-05-19T20:36:24.508+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-05-19T20:36:32.378+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T20:36:32.380+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/silver_s3.py", line 69, in process_parquet_files
    os.remove(file_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/disney_data_20240518T000000.parquet'
[2024-05-19T20:36:32.391+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=silver_s3, task_id=process_parquet_files, run_id=scheduled__2023-04-23T00:00:00+00:00, execution_date=20230423T000000, start_date=20240519T203624, end_date=20240519T203632
[2024-05-19T20:36:32.402+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 362 for task process_parquet_files ([Errno 2] No such file or directory: '/tmp/disney_data_20240518T000000.parquet'; 1625)
[2024-05-19T20:36:32.443+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T20:36:32.457+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T20:36:32.458+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
